name: "jaffle_shop"
version: "2.1.0"
config-version: 2

# If you're using the local Core path leave this as duckdb.
# If not, you should set your connection via dbt Cloud.
# If you're working with dbt Core and a cloud warehouse you'll need to setup a profile and configure it below.
# https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles
# The profiles.yml file is committed to the repo, DO NOT commit your credentials, use environment variables and a .env file
profile: "duckdb"
require-dbt-version: ">=1.6.0"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
