version: "3"

tasks:
  venv:
    cmds:
      - python -m venv .venv
      - source .venv/bin/activate

  install-cloud:
    cmds:
      - brew tap dbt-labs/dbt-cli
      - brew install dbt-cloud-cli
      - python -m pip install --upgrade pip
      - python -m pip install --progress-bar off -r requirements-cloud.txt
      - if [ -f profiles.yml ]; then rm -f profiles.yml; fi

  install-core:
    cmds:
      - python -m pip install --upgrade pip
      - python -m pip install --progress-bar off -r requirements-core.txt
      - if [ -f dbt_cloud.yml ]; then rm -f dbt_cloud.yml; fi

  setup:
    cmds:
      - dbt deps
      - dbt seed
